# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nlp_linkedin_examples.ipynb.

# %% auto 0
__all__ = ['analyze_one']

# %% ../nbs/00_nlp_linkedin_examples.ipynb 17
def analyze_one(df:pd.DataFrame, # dataframe with df.input
                candidate_labels, index ):
    i=index
    sequence = df.input[i]
    answer = classifier(sequence, candidate_labels)
    dfo = pd.DataFrame(answer)
    dfo.sort_values('scores',inplace=True)
    fig = px.bar(dfo, x="scores", y="labels", orientation='h')
    print(dfo.sequence[0])
    
    print('Actual Category: '+str(df.category[i]))
    print(fig.show())
